package com.apk.shopup.navigation

const val ROUT_HOME = "home"
const val ROUT_LOGIN = "login"
const val ROUT_SIGNUP = "signup"
const val ROUT_CONTACT = "contact"
const val ROUT_UPLOAD = "upload"
const val ADD_PRODUCTS_URL = "add_products"
const val VIEW_PRODUCTS_URL = "view_products"
const val HOME_URL = "home"
const val UPDATE_URL = "update"
const val ROUTE_PURCHASE = "purchase"
const val ROUTE_ADMIN = "admin"
const val ROUTE_DASH = "dash"
const val ROUTE_FIRSTHOME = "iscohome"
const val ROUTE_UPDATE = "UPDATE"
const val ROUTE_FIRSTORDER = "order"
const val ROUTE_ABOUT = "order"
const val ROUTE_DETAIL = "order"